name: vertx-sql-client (5.x)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 5 * * *'
jobs:
  CI:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            jdk: 8
            profile: 'PostgreSQL-9'
          - os: ubuntu-latest
            jdk: 8
            profile: 'PostgreSQL-10'
          - os: ubuntu-latest
            jdk: 8
            profile: 'PostgreSQL-11'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MySQL-8.0'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MySQL-5.6'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MySQL-5.7'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MariaDB-10.4'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MSSQL-2017-latest'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MSSQL-2019-latest'
          - os: ubuntu-latest
            jdk: 8
            profile: 'DB2-11.5'
          - os: ubuntu-latest
            jdk: 8
            profile: 'SQL-templates'
          - os: ubuntu-latest
            jdk: 17
            profile: 'PostgreSQL-11'
          - os: ubuntu-latest
            jdk: 17
            profile: 'MySQL-5.7'
          - os: ubuntu-latest
            jdk: 17
            profile: 'MariaDB-10.4'
          - os: ubuntu-latest
            jdk: 17
            profile: 'MSSQL-2019-latest'
          - os: ubuntu-latest
            jdk: 17
            profile: 'Oracle-21'
    uses: ./.github/workflows/ci.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      jdk: ${{ matrix.jdk }}
      os: ${{ matrix.os }}
      profile: ${{ matrix.profile }}
      deploy: ${{ matrix.jdk == '8' && matrix.os == 'ubuntu-latest' }}
    secrets: inherit
  Deploy:
    name: Deploy to OSSRH
    if: ${{ github.repository_owner == 'eclipse-vertx' && (github.event_name == 'push' || github.event_name == 'schedule') }}
    needs: CI
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      jdk: 8
    secrets: inherit
